apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apirest-web
  name: apirest-web  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apirest-web
  template:
    metadata:
      labels:
        app: apirest-web
    spec:
      containers:
      #- image: enriquecatala/fastapi-helloworld:v1
      - image: enriquecatala/fastapi-helloworld:latest
        name: fastapi-helloworld
        ports:
        - containerPort: 5000
        # Simplemente para diferenciarlos facilmente les ponemos variables diferentes
        env:
        - name: HELLOWORLD_ENV
          value: "Pon aqui lo que te de la gana :)"
        resources:
          limits:
            cpu: "1"
            memory: "100Mi"
          requests:
            cpu: 500m
            
