apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apirest-web
  name: apirest-web  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apirest-web
  template:
    metadata:
      labels:
        app: apirest-web
    spec:
      containers:
      - image: 897722709068.dkr.ecr.eu-north-1.amazonaws.com/backend-app:latest  # ECR image path with tag
        name: fastapi-helloworld
        ports:
        - containerPort: 5000
        env:
        - name: HELLOWORLD_ENV
          value: "Pon aqui lo que te de la gana :)"
        resources:
          limits:
            cpu: "1"
            memory: "100Mi"
          requests:
            cpu: 500m
