apiVersion: v1
kind: Service
metadata:  
  labels:
    app: apirest-web
  name: web-service
spec:
  ports:
  - name: http
    port: 50000        # The external port exposed on the LoadBalancer
    protocol: TCP
    targetPort: 5000   # The internal port where your application listens
  selector:
    app: apirest-web
  type: LoadBalancer   # Expose the service externally
