apiVersion: v1
kind: Service
metadata:  
  labels:
    app: web-service-clusterip
  name: web-service-clusterip  
spec:
  ports:
  - name: 50000-5000
    port: 50000
    protocol: TCP
    targetPort: 5000
  selector:
    app: apirest-web
  type: ClusterIP
