name: Backend App CI

on:
  push:
    paths:
      - 'app/**'         # Trigger on changes within the app folder
      - 'Dockerfile'     # Trigger on changes to the Dockerfile
      - 'manifests/**'   # Trigger on changes within the manifests folder
      - 'application.conf' # Trigger on changes to the application.conf file
      - 'docker-compose.yml' # Trigger on changes to the docker-compose.yml file
      - 'requirements.txt'   # Trigger on changes to the requirements.txt file
  pull_request:
    paths:
      - 'app/**'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        if: github.event_name == 'push'  # Optional: Only log in on pushes to avoid rate limiting in pull requests
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t backend-app:latest -f Dockerfile .

      - name: Run tests
        run: |
          # If you have tests, you can add commands here, e.g.:
          docker run backend-app:latest pytest /path/to/tests

      - name: Push Docker image
        if: github.event_name == 'push'  # Only push on push events (not on PRs)
        run: |
          docker tag backend-app:latest your-docker-repo/backend-app:latest
          docker push your-docker-repo/backend-app:latest
