name: Backend App CI

on: push
#  push:
#    paths:
#      - 'app/**'         # Trigger on changes within the app folder
#      - 'Dockerfile'     # Trigger on changes to the Dockerfile
#      - 'manifests/**'   # Trigger on changes within the manifests folder
#      - 'application.conf' # Trigger on changes to the application.conf file
#      - 'docker-compose.yml' # Trigger on changes to the docker-compose.yml file
#      - 'requirements.txt'   # Trigger on changes to the requirements.txt file
#  pull_request:
#    paths:
#      - 'app/**'
#      - 'Dockerfile'
#    branches-ignore:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t backend-app:latest -f Dockerfile .
